baseURL = 'https://conference.pyladies.com'
languageCode = 'en-us'
title = 'PyLadiesCon 2024'
theme = ["pyladies"]
summaryLength = 10
enableInlineShortcodes = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
weight = 20

[[menus.main]]
name = 'About PyLadiesCon'
pageRef = '/about'
parent = 'About'
weight = 21

[[menus.main]]
name = 'Volunteer'
pageRef = '/volunteer'
parent = 'About'
weight = 22

[[menus.main]]
name = 'Assets'
pageRef = '/assets'
parent = 'About'
weight = 23

[[menus.main]]
name = 'Speakers'
url = 'https://pretalx.com/pyladiescon-2024/speaker/'
weight = 30

[[menus.main]]
name = 'Schedule'
pageRef = '/schedule'
weight = 40

[[menus.main]]
name = 'Sponsors'
pageRef = '/sponsors'
weight = 50

[[menus.main]]
name = 'News'
pageRef = '/news'
weight = 60


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
